<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="garp_robot">

    <gazebo>
        <plugin 
            filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>garp/joint_states</topic>
        </plugin>

    <plugin
        filename="gz-sim-diff-drive-system"
        name="gz::sim::systems::DiffDrive">
        <topic>garp/cmd_vel</topic>
        <left_joint>base_TO_wh_l</left_joint>
        <right_joint>base_TO_wh_r</right_joint>
        <wheel_separation>${(chasis_len_y / 2.0 + wh_thick / 2.0 + wh_chasis_gap) * 2}</wheel_separation>
        <wheel_radius>${wh_radius}</wheel_radius>
    </plugin>
        
    </gazebo>
    

</robot>